### ISSUE TITLE
留言板虽然简单，但是丑啊。

### ISSUE THREAD

**Issue by KIDJourney** [sky-admin/FE-tutorial#6]

**Comment by KIDJourney** [comment]
数据可以直接用local storage做嘛

**Comment by sky-admin** [comment]
搞事情是不是啊……localstorage做还能叫留言板吗？记事板吧。。丑个毛线啊，，没有UI设计我们的审美水平就是这样的！

**Comment by KIDJourney** [comment]
demo啊，能本地看到效果就行了啊，讲道理留言板和记事版的区别不就是写到的地方（或者可见标记）不一样嘛。

**Comment by sky-admin** [comment]
我不管，我写了后端还不让用上啦？还有localstorage不需要学习成本吗。为什么不学真的呢。localstorage能做分页吗。能做查询吗。真能和这个请求真实后端的效果一样？你写个试试？

**Comment by KIDJourney** [comment]
好好好，你等着，我强行学一波。

**Comment by sky-admin** [comment]
来来来我等着，分页和查询，你做个毛线……做个搜狐版的假分页差不多……

**Comment by KIDJourney** [comment]
放学别走。

**Comment by sky-admin** [comment]
我不走我看着，你fork走写，写出来了我合进来。假的就假的吧。。
